"""
Spider 任务脚本生成器
根据任务配置生成可运行的 Spider Python 脚本（供 docker 容器内执行）
"""
import json

CLASS_NAMES = {
    "crawl": "CrawlTaskSpider",
    "single": "SingleTaskSpider",
    "sitemap": "SitemapTaskSpider",
    "xml": "XMLTaskSpider",
    "csv": "CSVTaskSpider",
    "shopify": "ShopifyTaskSpider",
}

BASE_CLASSES = {
    "crawl": "CrawlSpider",
    "single": "CrawlSpider",
    "sitemap": "SitemapSpider",
    "xml": "XMLFeedSpider",
    "csv": "CSVFeedSpider",
    "shopify": "ShopifySpider",
}

HEADER = '''# -*- coding: utf-8 -*-
"""Generated by Scrapling Web Console task generator."""
import json, os
from scrapling.spiders import (
    Spider, CrawlSpider, SitemapSpider, XMLFeedSpider, CSVFeedSpider,
    ShopifySpider, CrawlRule, LinkExtractor,
)
from scrapling.fetchers import FetcherSession, ProxyRotator

TASK_DIR = "/work/tasks/{task_id}"
ITEMS_FILE = os.path.join(TASK_DIR, "items.jsonl")
CACHE_DIR = os.path.join(TASK_DIR, "cache")
CONFIG = json.load(open(os.path.join(TASK_DIR, "task.json"), encoding="utf-8"))

def _save_item(item):
    try:
        with open(ITEMS_FILE, "a", encoding="utf-8") as f:
            f.write(json.dumps(item, ensure_ascii=False) + "\\n")
    except Exception:
        pass

def _extract_fields(response, fields, adaptive):
    item = {{"url": str(getattr(response, "url", ""))}}
    for f in fields:
        try:
            sel = f.get("selector") or ""
            if f.get("xpath"):
                node = response.xpath(f["xpath"])
            elif sel:
                node = response.css(sel, adaptive=adaptive)
            else:
                node = response
            attr = f.get("attr") or "text"
            if attr == "text":
                val = node.css("::text").get() if sel else None
            elif hasattr(node, "attr"):
                val = node.attr(attr)
            else:
                val = None
            item[f["name"]] = (val or "").strip() if isinstance(val, str) else val
        except Exception:
            item[f["name"]] = None
    return item
'''

def _proxy_setup(config):
    if config.get("proxy_rotation"):
        return '''        try:
            with open("/work/proxies.json", encoding="utf-8") as f:
                pool = json.load(f)
            proxies = []
            for p in pool:
                if p.get("ip") and p.get("ip") != "0.0.0.0" and p.get("port"):
                    proxies.append(f"{p.get('protocol', 'http')}://{p['ip']}:{p['port']}")
            if proxies:
                rotator = ProxyRotator(proxies=proxies[:200])
                manager.add("default", FetcherSession(proxy_rotator=rotator, timeout=30))
                return
        except Exception:
            pass
        manager.add("default", FetcherSession(timeout=30))'''
    return '''        manager.add("default", FetcherSession(timeout=30))'''

def _class_attrs(config):
    t = config["type"]
    attrs = []
    if t == "sitemap":
        attrs.append("    sitemap_urls = CONFIG.get('start_urls', [])")
    if t == "xml":
        attrs.append("    itertag = CONFIG.get('itertag', 'item')")
    if t == "csv":
        hdrs = config.get("csv_headers") or []
        attrs.append(f"    headers = {json.dumps(hdrs)}")
    if t == "shopify":
        tw = config.get("target_website", "")
        if tw:
            attrs.append(f"    target_website = {json.dumps(tw)}")
    return "\n".join(attrs)

def _rules_method(config):
    if config["type"] != "crawl":
        return "    def rules(self):\n        return []"
    rules = config.get("crawl_rules") or {}
    allow = rules.get("allow") or []
    deny = rules.get("deny") or []
    restrict = rules.get("restrict_css") or ""
    le_args = []
    if allow:
        le_args.append(f"allow={json.dumps(allow)}")
    if deny:
        le_args.append(f"deny={json.dumps(deny)}")
    if restrict:
        le_args.append(f"restrict_css={json.dumps(restrict)}")
    le = f"LinkExtractor({', '.join(le_args)})" if le_args else "LinkExtractor()"
    return (
        "    def rules(self):\n"
        f"        return [CrawlRule(link_extractor={le}, callback=self.parse_item)]\n"
    )

def _parse_method(config):
    t = config["type"]
    fields = json.dumps(config.get("fields") or [], ensure_ascii=False)
    adaptive = "True" if config.get("adaptive") else "False"
    fv = f"CONFIG.get('fields', [])"
    if t in ("crawl", "single"):
        if t == "crawl":
            return (
                "    async def parse_item(self, response):\n"
                f"        item = _extract_fields(response, {fv}, {adaptive})\n"
                "        _save_item(item)\n"
                "        yield item\n"
            )
        return (
            "    async def parse(self, response):\n"
            f"        item = _extract_fields(response, {fv}, {adaptive})\n"
            "        _save_item(item)\n"
            "        yield item\n"
        )
    if t == "sitemap":
        return (
            "    async def parse(self, response):\n"
            "        async for result in super().parse(response):\n"
            "            if isinstance(result, dict):\n"
            f"                item = _extract_fields(result, {fv}, {adaptive})\n"
            "                _save_item(item)\n"
            "                yield item\n"
            "            else:\n"
            "                yield result\n"
        )
    if t == "xml":
        return (
            "    async def parse_node(self, response, node):\n"
            "        item = {'url': str(getattr(response, 'url', ''))}\n"
            "        for f in CONFIG.get('fields', []):\n"
            "            try:\n"
            "                sel = f.get('selector') or ''\n"
            "                val = node.findtext(sel) if sel else None\n"
            "                item[f['name']] = (val or '').strip() if val else None\n"
            "            except Exception:\n"
            "                item[f['name']] = None\n"
            "        _save_item(item)\n"
            "        yield item\n"
        )
    if t == "csv":
        return (
            "    async def parse_row(self, response, row):\n"
            "        item = {'url': str(getattr(response, 'url', ''))}\n"
            "        for f in CONFIG.get('fields', []):\n"
            "            k = f.get('selector') or f.get('name')\n"
            "            item[f['name']] = row.get(k) if k else None\n"
            "        _save_item(item)\n"
            "        yield item\n"
        )
    if t == "shopify":
        return (
            "    async def parse(self, response):\n"
            "        async for result in super().parse(response):\n"
            "            if isinstance(result, dict):\n"
            "                _save_item(result)\n"
            "            yield result\n"
        )
    return ""

def gen_spider_script(config):
    task_id = config["id"]
    t = config["type"]
    cls = CLASS_NAMES.get(t, CLASS_NAMES["crawl"])
    base = BASE_CLASSES.get(t, "CrawlSpider")
    start_urls = json.dumps(config.get("start_urls") or [], ensure_ascii=False)
    domains = json.dumps(config.get("allowed_domains") or [], ensure_ascii=False)
    concurrency = int(config.get("concurrency", 4))
    delay = float(config.get("download_delay", 0.0))
    robots = "True" if config.get("robots_txt_obey") else "False"
    autothrottle = "True" if config.get("autothrottle") else "False"
    dev = "True" if config.get("development_mode") else "False"
    cache_dir = 'CACHE_DIR' if config.get("development_mode") else 'None'

    parts = [HEADER.format(task_id=task_id)]
    parts.append(f"\nclass {cls}({base}):")
    parts.append(f'    name = {json.dumps(task_id)}')
    parts.append(f"    start_urls = {start_urls}")
    parts.append(f"    allowed_domains = {domains}")
    parts.append(f"    concurrent_requests = {concurrency}")
    parts.append(f"    download_delay = {delay}")
    parts.append(f"    robots_txt_obey = {robots}")
    parts.append(f"    autothrottle_enabled = {autothrottle}")
    parts.append(f"    development_mode = {dev}")
    parts.append(f"    development_cache_dir = {cache_dir}")
    extra = _class_attrs(config)
    if extra:
        parts.append(extra)
    parts.append("")
    parts.append("    def configure_sessions(self, manager):")
    parts.append(_proxy_setup(config))
    parts.append("")
    parts.append(_rules_method(config))
    parts.append(_parse_method(config))
    parts.append("")
    parts.append(f"if __name__ == '__main__':")
    parts.append(f"    {cls}(crawldir=TASK_DIR, interval=10).start()")
    return "\n".join(parts)
